heitor-password: ENC[AES256_GCM,data:45BDreHqRqY4OsR8iCqRFq/3ms2eBZYfoyxAU0FpSToB5HATovfjGzGBPfM4FE/Lkl1Xpk4IZxEt7mkPbAZgyAAny3G5JwxSYg==,iv:bQyu0sxFFdDjMxKb907ZWo2oUQQq24a7TeYEC7giA50=,tag:CBWkRmu37OHE1zLE2dKz1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1k0qg6ah5cs36l2n5vaxymymxws8e4n4c0gv3wqgwkfq95h3vd9ysl33mee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc2t3ZE4zM25pZ1VZeU05
        eVk2NWkrM0JtZ0FhalE5blFVY0hvWEREZTA4CjhQb1J4YWMwZTB1UFFBTVQvRjVD
        ZnlYR0J6WXZBQTBKSG56U0RudWNmRzgKLS0tIFhCUDFHc0xwMGdrYVV1MXI5MGxt
        OE5lL1NCRkNDN24rc3FTMm5mZUEvUDgK95kRjoct0VTg/PkpuyRUvmPAXLtjU+p0
        YctQdS3myQtDWGXuvOXiMxuewMHL+0+IyuTWuQoinqEZtvQg4kJobA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T07:02:21Z"
  mac: ENC[AES256_GCM,data:PrCVChrNjL59Qr4IJTknrUn3hkItoHZjnZt+qp42LJbwF76KLS8nU2CnKDWpecZLCxFiOePGGQWvqmlCONXa1Y2q6WkWVRrSwtlFRvn0oRoyUo/IKq3t7UwJIgwkToxmcS4V3HX0yUs+CdgJsWUknwv+peZpwDcKUs9hMkDmqKE=,iv:KzDiBou/SAQLH7TfHBIiDLTL3hd9yVt7BPA0uaUrMkI=,tag:NheYEoKNY40lRGMWfSdrNA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
