heitor:
  nixos-builders-key: ENC[AES256_GCM,data:a9xD883ydPnIlFYyZaPjuKv9gkZLvZY/RP3OcWLnnn4Hmmtu3V2shyDUuYaLR13L1PRRrm1h20VNKCdNeypZXaT+wUdWBhJ5ctcRXkvhs8vcKixRw92DK5W5wAIX6SUCeA+8X7q0gQ7Ckrfu/QIP7M3mWozKtsM6jJk/vLh3hU2804X5EgsoSsQNZRQRxiExwab382mM4rWm32l67h5F9uuZmQIiUlW7a9h8Tev+6zNEeYw3ZTdr/mDGWBFQ0A2ptRxBLqhSpU7cbXMGtdyWksQDlMkESThPlAJj2iFpHxM5nDcUgIrX4/dpHf5Syyvg5OlGHjcrNvQvZ9P7ci0bF2HsczvEFPfxGJHZQqvVy47Rse/5XRN9iIafehFH6pGmnzWcmMKYOsxu1AqEsxBh5E0WM5yxzRIFJbiRxIj5VgPDStLWg6veryy5dCE5zvE/IQXSU9ywJvBP1ysxQyWpYmcIfbWSwricWclQn0WNJkhnjhU7xMgxN08pzRYoJgj03L/Mg4in4nKuUYZ24FQy,iv:OeYaJz/9r5ltRaV/twQNVGBruNPGw42qmw0KVv7iZGg=,tag:Bs54uhqQuAqczKVvkXaU2g==,type:str]
  darwin-builders-key: ENC[AES256_GCM,data:dx6yfDFu5x4hPnRgcz3NkUTMjMhOXiIh0kskYwTEPDF+vnGrRVhBYyJQlNs27eD00cThX+F3YzAICXBYELxSh8M9CL3PU54a9GDMErhthuk87hrUs9Dzs3zcuE0E2l6ZoX/5s1GsvCJPzz8lsM2v3qOMCh46hcIunXM3JkBGfK+5KHq6Akb1B3NXNM7QWkdhQrk4z/zgGK79dueNuLVmJ/RPkWDbcv7pPhNp+3f/ljgaBjn+lGfF3iyF/YN1Q478OU7zhAbJ7u+xfMSXFYqlVONH6Ri/jWaLIWQrlte2xuFHxvdtEVec20RRSxW/s4M7m/jGdIuZIiktUD0T5hkzph0JGWZ9ATWjQHeJIiEw93Uc/GOFSa1QLsNg7DSWSbxxtXqbhmmQ/bxJua1k6yQO2zaYVWv5wBZgs4u6bJg+pt9L81xa47UugaAU4XL0V7mr4F1fLB3kY2K3NjMi++OyFfM9SHjyQt0eg70cWpcOcZDEfddiyR8nxT3Qt8/eLfJhEkmGfANX5jUZadWUU+NC,iv:FV8IY3V5reGlqRsrXXgk44d+zwWALI+lqWkCfCyGZEU=,tag:4JZYI0/m3fpUo24+pdLABw==,type:str]
  password: ENC[AES256_GCM,data:FYTZZt0A+3iSNJi+koMN+d8AtzzCDecGuxtxGqqQdIjqpaQ0ZLW86TjEN9ZDgypMbOOU+YPylKzV9+AU6uprpEu+U9JV6sECgg==,iv:494j9CvsrrH4sXiZDjIP+uIde1QUFRKhy+C6icKmfkw=,tag:f6W3ijKuPRwc80htXyQhVg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1k0qg6ah5cs36l2n5vaxymymxws8e4n4c0gv3wqgwkfq95h3vd9ysl33mee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc2t3ZE4zM25pZ1VZeU05
        eVk2NWkrM0JtZ0FhalE5blFVY0hvWEREZTA4CjhQb1J4YWMwZTB1UFFBTVQvRjVD
        ZnlYR0J6WXZBQTBKSG56U0RudWNmRzgKLS0tIFhCUDFHc0xwMGdrYVV1MXI5MGxt
        OE5lL1NCRkNDN24rc3FTMm5mZUEvUDgK95kRjoct0VTg/PkpuyRUvmPAXLtjU+p0
        YctQdS3myQtDWGXuvOXiMxuewMHL+0+IyuTWuQoinqEZtvQg4kJobA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T21:49:17Z"
  mac: ENC[AES256_GCM,data:OLd10/wslJhV9GMAhlrkHG4eYJY8cPPS7XA7x91b2iezSwZglG6zPy74zUs0aVJ3d0huy45froDf8j3Vl3/gckYv1G8TF9U0Jr/Hjv8BmCy23WiQbskCRanHJmWdtK6hPPZeHGRpi9bP0R8v5o7vATDjFz6y4YroGUiAtRrk2UM=,iv:/Meb6PoXIJSPJoG280DQMuC5Il2twm3OhzOXRza3lMA=,tag:NerVngeZNHCUhxrGFKT73g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
