password: ENC[AES256_GCM,data:V/f+olCB3yMkoJI62qj8IOgC+QL/8dfA8xzdnKr6rlqXPGQqTWh+NF91XFf7/SMDx5z5pkI50NJNUpnQpmY8I+gyExXvJNw7jw==,iv:dI34eI5lH+I+agib4j5e/3zAn6RzYwNN4do6XBdoja0=,tag:w9kNlyb0hj2KlyO1WRspLA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1md83kpt80rp0p03fvcutelmvjgavaefjlcq5nn6kjg5zjgp94ydsks4tn8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc3RoMmYvUktBZUtPaG1m
        YVhmYXIvYUQyNlFOZk8xR1dWZUVPam51dUZBCjlUbVdPbTR3aXpDQnp1Zm9tZ0NB
        RmFHQnlBWmlJOC8yNGdLOWt5K2pidmMKLS0tIGNGWGdnL21EQWJxMUNDMGhEdzhI
        dTh3dTArYy8xLzh4YXplb3dpNUM0YkEKT38rICNUmia6MW5dDt1K7FVYOrUWlSiq
        NvvfpjvLBksxeJMJgdqW3mbXxRhgqjpqDjz7YswfoAOyp5/ONI5H3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T01:12:02Z"
  mac: ENC[AES256_GCM,data:lEmdfW5P5bEZUlbQ+0Hj5Yuu4IaQ5GKepd6PaRhXdcfS7kqRIPF5bOufWMmASWTgJOTlf/OaJRJ1oXbLS2S0RBi/dy4sNrUY0eEP9JBwSSAgqTTT0bpgvYXHCJDHccu2FyHZzxhN/drKGB1o/ALPXQOeWUqFJAh2vYS7csVGIWE=,iv:KF1matTlH1yBWUlRAOQ5etfTzyt7Gxq7qLAcLuTo4nk=,tag:+7s4gvg9SU87MRbIDVkIaw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
