name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Run `nix flake check`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators
            extra-substituters = https://cosmic.cachix.org
            extra-trusted-public-keys = cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=
      - name: Check flake
        run: nix flake check

  build-hosts:
    name: Build NixOS configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - axolotl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators
            extra-substituters = https://cosmic.cachix.org
            extra-trusted-public-keys = cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=
      - name: Build NixOS configuration for ${{ matrix.host }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --no-link \
            --keep-going \
            --print-build-logs
